### PR TITLE
feat: upgrade to eslint 7

### PR DESCRIPTION
**Pull request by G-Rath**
BREAKING CHANGE

This is mostly good to go, I just need to do some dogfooding against my typescript projects (I should probably write a script for that tbh 🤔)

~We're now technically using some deprecated rules that've been moved to `eslint-plugin-node`, but I'm going to move them over in another PR (to be merged *before* this one), as while a few are node-context-specific, the majority are useful in webpack/bundle context (i.e the require rules) so we should just add it to `index.js`.~

### CODE REVIEW

**Comment by Rabid-Dan** [comment]
How badly will this break/what kind of breakages should we expect in apps using this?

**Comment by G-Rath** [comment]
"breaking" is actually a bit of a strong word here - the main break is that it's technically dropping support for Node 8 (via eslint), which none of our applications should be using as it's been EOL for almost a year now (let alone any app that would be using this config, as we've not got a lot migrated to it yet).

The changes to the recommends we use are not particularly drastic - `eslint` only includes rules that find actual errors in their recommended, and the `@typescript-eslint` recommendations are mostly the same with a light sprinkle of agreed best practices.

Running over my repos has only produced a few new linting errors from `@typescript-eslint`, specifically `ban-type` which now includes `object` (which is replaceable with `Record<string, unknown>`).

**Comment by G-Rath** [comment]
I've included adding `eslint-plugin-node` to the main config, as a nicety (vs doing it in a minor) - this doesn't make it any more breaking as it's just for using the updated versions of the node rules that they moved to said plugin as part of ESLint 7.

We are enabling `no-deprecated-apis`, but that's not breaking for the reasons mentioned in my previous comment: it looks for the `engines` field in `package.json`, and if that's not set defaults to Node 8+, so it won't cause problems for our modern apps.

**Comment by G-Rath** [comment]
I'm going to put this on hold until `@typescript-eslint` 4 is released, which should be in about 2 weeks, just so that we can save on majors.

**Review by tklarryonline — APPROVED** [review]

**Pull request merged**
